### PR TITLE
remove links to runtimes to workaround issue 1814

### PR DESCRIPTION
**Pull request by zzDRT**

### CODE REVIEW

**Comment by SirSpidey** [comment]
I don't work with this content at all, so I'm not comfortable approving the change. 
We do have a similar issue with the /services/[watson](https://console.stage1.bluemix.net/docs/services/watson/index.html) toc. See the **Docs** topicgroup under reference

Also, could use a link to issue 1814. Didn't find it in doc framework or content.

cc @jenschlot @sefuhrer @msochka

**Comment by msochka** [comment]
@SirSpidey 

Allen, I updated the file. I removed the files from the TOC and placed xrefs in a topic that covers the runtime environments. I prefer not to remove these files entirely, which is what merging the pull request would have done. I'm not sure how to reject this pull request, but you can take a look now on production or staging to see if you are OK with my fix. Thanks for your patience. I was away at a funeral last week and am only just sifting through all the urgent issues.

Best,

Mike

cc:  @jenschlot @sefuhrer

**Comment by zzDRT** [comment]
Thanks @msochka

**Comment by SirSpidey** [comment]
Full link to related issue: https://github.ibm.com/Bluemix/docs/issues/1814

**Comment by SirSpidey** [comment]
Hi @msochka, I don't have any skin in the particular fix for predictive modeling, but I do suffer from the bug. So I piled on to [#1814](https://github.ibm.com/Bluemix/docs/issues/1814).

**Pull request closed without merging**
